release(dotnet-sdk): v0.2.2 w/ the OpenFgaClient & BatchCheck
openfga/sdk-generator pull request #104
Opened 2023-04-05 23:10 UTC by rhamzeh

## Description

## References

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2023-04-06 18:55 UTC, adriantam approved these changes

2023-04-06 20:40 UTC, adriantam submitted a review, later dismissed

2023-04-12 15:00 UTC, adriantam commented on config/common/config.base.json
> +  "defaultMaxRetry": 15,
we bump this to 15 but in our change lot we say it is 5?

2023-04-12 15:07 UTC, adriantam requested changes

2023-04-12 15:07 UTC, adriantam commented on config/clients/dotnet/CHANGELOG.md.mustache
> +- chore(config): bump default max retries to `5`
```suggestion
- chore(config): bump default max retries to `15`
```

2023-04-12 15:10 UTC, rhamzeh commented on config/clients/dotnet/template/api_test.mustache
> +        /// Test ListStores does not crash in error handling
We already do:
```csharp
var error = await Assert.ThrowsAsync<FgaApiNotFoundError>(ApiError);

            Assert.Equal(error.Method, HttpMethod.Get);
            Assert.Equal("ListStores", error.ApiName);
            Assert.Equal($"{_config.BasePath}/stores", error.RequestUrl);
            Assert.Null(error.StoreId);
```

2023-04-12 15:17 UTC, adriantam commented on config/clients/dotnet/template/api_test.mustache
> +        /// Test ListStores does not crash in error handling
In this case, maybe the description should be assert proper error is returned?

2023-04-12 15:19 UTC, adriantam submitted a review, later dismissed

2023-04-12 15:21 UTC, adriantam approved these changes

2023-04-12 15:28 UTC, merged