fix(java-sdk): fix publishing to maven central
openfga/sdk-generator pull request #210
Opened 2023-09-19 17:32 UTC by rhamzeh

## Description

## References

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2023-09-20 18:47 UTC, booniepepper commented on config/clients/java/template/publish.gradle.mustache
> +            url = 'https://s01.oss.sonatype.org/content/repositories/snapshots/'
This feels off. Snapshots are typically used for internal development and use (semantically) mutable versions with a `-SNAPSHOT` suffix

2023-09-21 16:21 UTC, booniepepper requested changes

2023-09-21 16:28 UTC, booniepepper approved these changes

2023-09-21 16:33 UTC, booniepepper approved these changes

2023-09-21 16:44 UTC, adriantam approved these changes

2023-09-21 16:50 UTC, merged